"""Danger Guard — PreToolUse hook: block destructive + undeclared operations.

Blocks:
  - Force push to main/master
  - rm -rf on non-temp paths
  - DROP TABLE / DROP DATABASE in sqlite3/psql
  - git reset --hard on main/master
  - settings.local.json / settings.json deletion or overwrite
  - .claude/hooks/ file deletion
  - .claude/state/ file deletion
  - Undeclared code changes (Edit/Write without current_task.json)
  - Undeclared work commands (Bash python/pytest/script without task declaration)

Must complete in <50ms (PreToolUse constraint).
Uses fast string matching — no file I/O in hot path.
"""

import json
import os
import sys
from pathlib import Path

# Fast substring matches — no regex for speed
FORBIDDEN_PATTERNS = [
    # Force push to protected branches
    ("git", "push", "--force", "main"),
    ("git", "push", "--force", "master"),
    ("git", "push", "-f", "main"),
    ("git", "push", "-f", "master"),
    # Destructive git on main
    ("git", "reset", "--hard", "main"),
    ("git", "reset", "--hard", "master"),
    # Recursive delete outside temp
    ("rm", "-rf", "/"),
    ("rm", "-rf", "~"),
    # Drop database
    ("DROP", "TABLE"),
    ("DROP", "DATABASE"),
    ("TRUNCATE", "TABLE"),
]

# Bash patterns that signal "work" — requires task declaration
WORK_TRIGGERS = [
    "python -c",
    "python -m",
    "python scripts/",
    "python -m pytest",
    "pytest",
    "PYTHONPATH=",
    "timeout ",
]

# Bash commands that are always safe (no declaration needed)
SAFE_PREFIXES = [
    "ls ", "cat ", "head ", "tail ", "find ", "grep ", "wc ",
    "mkdir ", "cp ", "mv ", "rm ", "echo ", "tee ",
    "which ", "where ", "npm list", "npm view", "npm install",
    "git ", "taskkill", "tasklist", "netstat", "ping ",
    "powershell", "start ", "npx ", "node --version",
    "pip ", "diff ", "sort ", "uniq ", "export ",
]

PROTECTED_PATHS = [
    ".claude/settings.local.json",
    ".claude/settings.json",
    ".claude/hooks/",
    ".claude/state/",
    ".claude/backups/",
]


def _load_dependency_map():
    """Load the hook dependency map generated by integrity_check.py. Returns {} on failure."""
    import json
    try:
        workspace_root = Path(__file__).resolve().parent.parent.parent
        dep_map_path = workspace_root / ".claude" / "state" / "hook_dependency_map.json"
        if dep_map_path.exists():
            with open(dep_map_path, "r", encoding="utf-8") as f:
                return json.loads(f.read())
    except Exception:
        pass
    return {}


def _warn_external_dependency(targeted):
    """If the targeted path is a hook with external dependencies, print context to stderr.

    Helps auditors understand WHY a hook file should not be deleted —
    e.g. 'pre_session.py is called by start.bat:12 — deletion breaks bat-file launch.'
    """
    # Extract filename from targeted path
    hook_name = targeted.replace("\\", "/").rstrip("/")
    if "/" in hook_name:
        hook_name = hook_name.rsplit("/", 1)[-1]

    dep_map = _load_dependency_map()
    hooks_info = dep_map.get("hooks", {})
    info = hooks_info.get(hook_name) or hooks_info.get(hook_name.replace(".py", "") + ".py")

    if info:
        callers = info.get("external_callers", [])
        extra = info.get("discovered_extra_callers", [])
        all_callers = callers + extra
        impact = info.get("deletion_impact", "")
        method = info.get("discovery_method", "")

        if all_callers:
            sys.stderr.write(f"  → External callers: {', '.join(all_callers)}\n")
        if impact:
            sys.stderr.write(f"  → Impact: {impact}\n")
        if method:
            sys.stderr.write(f"  → Discovered via: {method}\n")
        if not all_callers and not impact:
            sys.stderr.write(f"  → No external callers recorded, but check dependency map before deleting\n")
    else:
        sys.stderr.write(f"  → {hook_name} has no entry in dependency map — cannot verify external callers\n")


def _is_safe_bash(command):
    """Check if a Bash command is safe (read-only or infrastructure)."""
    cmd_stripped = command.strip()
    for prefix in SAFE_PREFIXES:
        if cmd_stripped.startswith(prefix):
            return True
    return False


def _is_work_bash(command):
    """Check if a Bash command performs 'work' that needs task declaration.

    Work = running scripts, tests, or executing Python code.
    Not work = read-only queries, file ops, git operations, package management.
    """
    if _is_safe_bash(command):
        return False
    for trigger in WORK_TRIGGERS:
        if trigger in command:
            return True
    return False


def _any_task_declared():
    """Check if any current_task.json exists and is valid at any location.

    Returns True if at least one location has a valid task declaration.
    Does NOT check file coverage — just checks existence.
    """
    paths = _get_task_file_paths()
    seen = set()
    for _label, task_path in paths:
        if task_path in seen:
            continue
        seen.add(task_path)
        task = _load_task_file(task_path)
        if task is not None:
            return True
    return False


def check_protected_path(args_str):
    """Check if command targets protected filesystem paths. Returns matching path or None.

    Only matches paths appearing as command arguments (after cp/mv/rm/tee or > redirect),
    NOT paths appearing inside string literals or Python code.
    """
    # Check explicit command targets: cp/mv/rm/tee + path
    for cmd_prefix in ("cp ", "mv ", "rm ", "tee "):
        idx = args_str.find(cmd_prefix)
        if idx == -1:
            continue
        rest = args_str[idx + len(cmd_prefix):].strip()
        for path in PROTECTED_PATHS:
            if rest.startswith(path) or rest.startswith(path.replace("/", "\\")):
                return path

    # Check > redirect targets
    if ">" in args_str:
        import re
        for m in re.finditer(r'\d?\>\s*(\S+)', args_str):
            rt = m.group(1).strip('"').strip("'")
            for path in PROTECTED_PATHS:
                if rt == path or rt.startswith(path):
                    return path
    return None


def _validate_restore_source(command):
    """Extract source path from cp/mv command and verify it's a legitimate backup source."""
    parts = command.split()
    for i, part in enumerate(parts):
        if part in ("cp", "mv") and i + 1 < len(parts):
            src = parts[i + 1].strip('"').strip("'")
            if "/backups/hooks/" in src or "/.claude/hooks/" in src:
                return True
    return False


def check_forbidden(command):
    """Check entire command string for forbidden patterns."""
    cmd_upper = command.upper()
    for pattern in FORBIDDEN_PATTERNS:
        pattern_upper = tuple(p.upper() for p in pattern)
        if all(p in cmd_upper for p in pattern_upper):
            return " ".join(pattern)
    return None


def _get_task_file_paths():
    """Return list of (label, path) tuples to check for current_task.json.

    Checks three locations to handle the CWD ambiguity:
      1. Relative to CWD (backward compatible — could be workspace or project)
      2. Workspace-level: derived from this hook file's own location
      3. Project-level: projects/marketmind/.claude/state/current_task.json
         (explicit, so both locations are checked even when CWD == workspace root)
    """
    paths = []

    # 1. Relative to CWD (backward compatible)
    cwd_path = os.path.join(os.getcwd(), ".claude", "state", "current_task.json")
    paths.append(("cwd", cwd_path))

    # 2. Workspace-level (derived from hook location)
    # This file: E:/AI_Studio_Workspace/.claude/hooks/danger_guard.py
    # parent.parent.parent -> workspace root
    workspace_root = Path(__file__).resolve().parent.parent.parent
    workspace_path = str(workspace_root / ".claude" / "state" / "current_task.json")
    paths.append(("workspace", workspace_path))

    # 3. Project-level (explicit, covers the case where CWD == workspace root
    #    but a separate project-level file exists)
    project_path = str(workspace_root / "projects" / "marketmind" / ".claude" / "state" / "current_task.json")
    paths.append(("project", project_path))

    return paths


def _load_task_file(path):
    """Load and validate a current_task.json. Returns dict or None."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            task = json.loads(f.read())
    except (OSError, json.JSONDecodeError, UnicodeDecodeError):
        return None
    task_type = task.get("type", "")
    task_files = task.get("files", [])
    if not task_type or not task_files:
        return None
    return task


def _is_file_covered(task, file_path_norm):
    """Check if a task declaration covers the given file."""
    task_files = task.get("files", [])
    file_basename = file_path_norm.split("/")[-1]
    return any(file_basename in tf or tf in file_path_norm for tf in task_files)


def check_task_declaration(file_path):
    """Verify current_task.json exists and is fresh before code changes.

    Checks THREE locations to handle the CWD ambiguity:
      1. .claude/state/current_task.json relative to CWD (backward compat)
      2. Workspace-level (derived from this hook file's location via __file__)
      3. Project-level (projects/marketmind/.claude/state/current_task.json)

    If ANY location has a valid declaration covering the target file,
    the check passes. Each location is independent — no sync is performed
    (they may serve different scopes/tasks).

    Returns (ok, error_msg). ok=True means proceed, ok=False means block.
    """
    if not file_path or not file_path.endswith(".py"):
        return True, ""
    # Skip test files and .claude/ internal files
    fp_norm = file_path.replace("\\", "/")
    if "/tests/" in fp_norm or "/.claude/" in fp_norm:
        return True, ""

    paths = _get_task_file_paths()

    # Try each path; allow if ANY covers the target
    seen_paths = set()
    for label, task_path in paths:
        if task_path in seen_paths:
            continue
        seen_paths.add(task_path)
        task = _load_task_file(task_path)
        if task is None:
            continue
        if _is_file_covered(task, fp_norm):
            return True, ""

    # Neither location had a valid covering declaration
    tried = " or ".join(p for _, p in paths)
    file_basename = fp_norm.split("/")[-1]
    return False, (
        f"File '{file_basename}' not covered by current_task.json at any location ({tried}). "
        f"Update task declaration before editing."
    )


def main():
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            sys.exit(0)

        data = json.loads(raw)
    except (OSError, EOFError, json.JSONDecodeError):
        sys.exit(0)

    tool_name = data.get("tool_name", "")
    tool_input = data.get("tool_input", {})

    # ── Continuous execution enforcement ────────────────────────────────
    # Block unnecessary confirmation-seeking during active task execution.
    # When a valid task is declared, "要开始吗/要继续吗" questions waste user time.
    if tool_name == "AskUserQuestion":
        if _any_task_declared():
            questions = tool_input.get("questions", [])
            for q in questions:
                q_text = q.get("question", "")
                # Match confirmation-seeking patterns
                if any(phrase in q_text for phrase in (
                    "要开始", "要继续", "可以开始", "可以继续",
                    "要不要", "是否继续", "是否开始", "开始吗", "继续吗",
                    "做吗", "行吗", "可以吗", "要不要做",
                )):
                    sys.stderr.write(
                        "BLOCKED: Continuous execution is active. "
                        "Do not ask for confirmation between steps — auto-proceed.\n"
                        f"  Question: {q_text[:100]}\n"
                    )
                    sys.exit(2)

    # Only check Bash, Write, Edit, Agent tools
    if tool_name not in ("Bash", "Write", "Edit", "Agent", "AskUserQuestion"):
        sys.exit(0)

    command = tool_input.get("command", "")
    file_path = tool_input.get("file_path", "")

    # ── Task declaration enforcement ───────────────────────────────────
    # Write/Edit to Python files: file must be covered by task declaration
    if tool_name in ("Write", "Edit"):
        ok, err = check_task_declaration(file_path)
        if not ok:
            sys.stderr.write(f"BLOCKED: {err}\n")
            sys.stderr.write("Run: write .claude/state/current_task.json with {{'type':'...','files':[...]}}\n")
            sys.exit(2)

    # Bash work commands: ANY task must be declared (don't work blind)
    if tool_name == "Bash" and command and _is_work_bash(command):
        if not _any_task_declared():
            sys.stderr.write(
                "BLOCKED: Bash work command requires task declaration. "
                "Update .claude/state/current_task.json before running scripts/tests.\n"
            )
            sys.stderr.write(f"  Command: {command[:120]}\n")
            sys.exit(2)

    # Agent calls with implementation intent: task declaration required
    if tool_name == "Agent":
        subagent = tool_input.get("subagent_type", "")
        prompt = tool_input.get("prompt", "")
        # Explore agents are read-only — always allow
        if subagent in ("Explore",):
            pass
        # All other agents require task declaration
        elif prompt and not _any_task_declared():
            sys.stderr.write(
                "BLOCKED: Agent call requires task declaration. "
                "Update .claude/state/current_task.json before spawning agents.\n"
            )
            sys.stderr.write(f"  Subagent: {subagent}\n")
            sys.exit(2)

    if not command and not file_path:
        sys.exit(0)

    # Check command for forbidden patterns
    forbidden = check_forbidden(command)
    if forbidden:
        sys.stderr.write(f"BLOCKED: Forbidden pattern '{forbidden}' in command: {command[:200]}\n")
        sys.exit(2)

    # Check for protected path targeting
    targeted = check_protected_path(command + file_path)
    if targeted:
        # Write/Edit to protected paths always blocked
        if tool_name in ("Write", "Edit"):
            _warn_external_dependency(targeted)
            sys.stderr.write(f"BLOCKED: Cannot modify protected path '{targeted}' via {tool_name}\n")
            sys.exit(2)
        if tool_name == "Bash":
            # Allow cp/mv restore FROM legitimate backup/hook sources TO protected dirs
            is_restore = _validate_restore_source(command) and targeted in (
                ".claude/hooks/", ".claude/state/", ".claude/backups/"
            )
            if is_restore:
                sys.exit(0)
            # Only block destructive operations that specifically target the matched path
            if "rm " in command or "tee " in command:
                sys.stderr.write(f"BLOCKED: Cannot delete/overwrite protected path '{targeted}'\n")
                sys.exit(2)
            # Check > redirect: only block if redirect target is the protected path itself
            if ">" in command:
                import re
                for m in re.finditer(r'\d?\>\s*(\S+)', command):
                    rt = m.group(1).strip('"').strip("'")
                    if rt in ('&1', '&2', '/dev/null', '/dev/stdout', '/dev/stderr'):
                        continue
                    if any(p in rt for p in PROTECTED_PATHS):
                        sys.stderr.write(f"BLOCKED: Cannot redirect to protected path '{rt}'\n")
                        sys.exit(2)
                sys.stderr.write(f"BLOCKED: Cannot delete/overwrite protected path '{targeted}'\n")
                sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()
