"""Chat handler — conversational AI for the dashboard chat box.

Session-based conversation management with DeepSeek Pro backend.
Each browser tab gets a unique session_id; history persists in-memory
for the lifetime of the API server process.
"""
from __future__ import annotations

import logging
import os as _os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger("marketmind.api.chat_handler")

MAX_HISTORY = 40  # messages per session (20 user + 20 assistant)
SESSION_TTL = 3600 * 4  # 4 hours


def _lang_instruction(lang: str = "") -> str:
    if not lang:
        lang = _os.environ.get("MARKETMIND_LANG", "zh")
    lang_map = {
        "zh": "所有输出必须使用中文。",
        "en": "All output must be in English.",
        "ja": "すべての出力は日本語で記述すること。",
        "ko": "모든 출력은 한국어로 작성해야 합니다.",
        "es": "Toda la salida debe estar en español.",
        "fr": "Toute sortie doit être en français.",
        "ru": "Весь вывод должен быть на русском языке.",
        "ar": "يجب أن يكون كل المخرجات باللغة العربية.",
        "de": "Alle Ausgaben müssen auf Deutsch sein.",
    }
    return lang_map.get(lang, "所有输出必须使用中文。")


CHAT_SYSTEM_PROMPT = """你是 MarketMind 投资分析平台的主 AI 分析师。你的职责是与用户进行投资相关的对话。

## 你的能力
- 分析全球宏观市场趋势、行业动态、个股基本面和技术面
- 解读市场数据、经济指标、公司财报
- 回答关于投资策略、风险管理、资产配置的问题
- 提供审慎、有依据的投资见解

## 规则
1. 基于数据和逻辑进行分析，不提供无依据的猜测
2. 如果你不知道某事，坦诚说明，不要编造
3. 不提供具体的买卖建议或价格目标（合规要求）
4. 可以讨论趋势、风险因素、情景分析
5. 回答简洁有力，避免冗长
6. {lang_instruction}

## 当前角色
你是用户的投资分析对话伙伴。用户可能会：
- 询问市场观点和分析
- 讨论投资想法
- 要求解释金融概念
- 获取实时管线状态更新

请用专业但友好的语气回复，像一位经验丰富的分析师与客户对话。"""


@dataclass
class ChatSession:
    session_id: str
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    messages: list[dict[str, str]] = field(default_factory=list)
    last_active: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def add_message(self, role: str, content: str) -> None:
        self.messages.append({"role": role, "content": content})
        self.last_active = datetime.now(timezone.utc).isoformat()
        if len(self.messages) > MAX_HISTORY:
            self.messages = self.messages[-MAX_HISTORY:]

    def touch(self) -> None:
        self.last_active = datetime.now(timezone.utc).isoformat()


class ChatManager:
    """In-memory chat session manager."""

    def __init__(self):
        self._sessions: dict[str, ChatSession] = {}

    def get_or_create(self, session_id: str) -> ChatSession:
        if session_id not in self._sessions:
            self._sessions[session_id] = ChatSession(session_id=session_id)
        else:
            self._sessions[session_id].touch()
        self._prune()
        return self._sessions[session_id]

    def get_history(self, session_id: str) -> list[dict[str, str]]:
        session = self._sessions.get(session_id)
        if session is None:
            return []
        session.touch()
        return list(session.messages)

    def clear(self, session_id: str) -> None:
        self._sessions.pop(session_id, None)

    def _prune(self) -> None:
        now = datetime.now(timezone.utc).isoformat()
        stale = [
            sid for sid, s in self._sessions.items()
            if s.last_active < now[:19]  # simple TTL check (approximate)
        ]
        # Only prune sessions older than SESSION_TTL
        for sid in list(self._sessions.keys()):
            try:
                age = (datetime.now(timezone.utc) - datetime.fromisoformat(self._sessions[sid].last_active)).total_seconds()
                if age > SESSION_TTL:
                    del self._sessions[sid]
            except (ValueError, KeyError):
                pass


_chat_manager: ChatManager | None = None


def get_chat_manager() -> ChatManager:
    global _chat_manager
    if _chat_manager is None:
        _chat_manager = ChatManager()
    return _chat_manager


async def chat_response(session_id: str, message: str, lang: str = "") -> dict[str, Any]:
    """Process a chat message and return AI response.

    Args:
        session_id: Browser session identifier (generated by frontend).
        message: User's chat message text.
        lang: Language code override (e.g. 'zh', 'en'). Reads from env var if empty.

    Returns:
        dict with keys: response, session_id, message_count
    """
    from marketmind.gateway.async_client import chat_pro

    manager = get_chat_manager()
    session = manager.get_or_create(session_id)
    session.add_message("user", message)

    system_prompt = CHAT_SYSTEM_PROMPT.format(
        lang_instruction=_lang_instruction(lang)
    )

    # Build messages array for the API call
    api_messages = [{"role": "system", "content": system_prompt}]
    api_messages.extend(session.messages[-MAX_HISTORY:])

    # Format as a single user_prompt for the chat_pro interface
    # We construct a conversation transcript for the model
    transcript_parts = []
    for msg in api_messages:
        if msg["role"] == "system":
            transcript_parts.append(f"[System]\n{msg['content']}")
        elif msg["role"] == "user":
            transcript_parts.append(f"[用户]\n{msg['content']}")
        elif msg["role"] == "assistant":
            transcript_parts.append(f"[分析师]\n{msg['content']}")

    user_prompt = "\n\n---\n\n".join(transcript_parts)

    try:
        result = await chat_pro(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=0.7,
            max_tokens=4096,
            reasoning_effort="low",
        )
        response_text = result.get("content", "") if isinstance(result, dict) else str(result)
        if not response_text:
            response_text = "抱歉，我暂时无法回应。请稍后再试。"

        session.add_message("assistant", response_text)

        return {
            "response": response_text,
            "session_id": session_id,
            "message_count": len(session.messages),
        }
    except Exception as e:
        logger.warning("Chat API call failed: %s", e)
        fallback = "抱歉，AI 服务暂时不可用，请稍后重试。"
        session.add_message("assistant", fallback)
        return {
            "response": fallback,
            "session_id": session_id,
            "message_count": len(session.messages),
            "error": str(e),
        }
