"""
shadow_pipeline_orchestrator.py — Phase 8.1 Daily Shadow Run Pipeline Orchestrator

Two-stage production-grade pipeline for daily shadow mode execution:

  Day T  (snapshot): MarketDataReplayer → ShadowAggregator → ZeroHedgingValidator
                     → EventStore.append_prediction/batch → ShadowFormatter
  Day T+1 (reconciliation): MarketDataReplayer(actuals) → ShadowTribunal
                            → EventStore.append_verdict → ShadowFormatter(tribunal)

Immutable append-only discipline: every prediction, batch, and verdict is written
to the EventStore as a single fsync'd JSONL line.  No overwrites, no deletes.

Architecture:
  Orchestrator pattern — delegates to existing Phase 8 modules without modifying
  their interfaces.  Pure composition, no inheritance.

SPARC:
  Specification: daily shadow run pipeline with Day T / Day T+1 split.
  Pseudocode: dataclass results → orchestrator class → three entry points.
  Architecture: facade over aggregator/validator/tribunal/formatter/store.
  Refinement: immutable event sourcing enforced at every write boundary.
  Completion: passed full pipeline test.
"""

from __future__ import annotations

import datetime
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.event_store import EventStore
from src.market_data_replayer import MarketDataReplayer
from src.shadow_aggregator import ShadowAggregator
from src.shadow_formatter import ShadowFormatter, ShadowReport, TribunalSummary
from src.shadow_tribunal import ShadowTribunal
from src.shadow_types import BatchShadowRun, ShadowMode, ShadowScenario, TribunalVerdict
from src.zero_hedging_validator import ZeroHedgingValidator

logger = logging.getLogger(__name__)

# Default watch pool (mirrors main.py)
DEFAULT_SHADOW_POOL: List[str] = [
    "IAU", "GDX", "GLD", "SLV",
    "TLT", "IEF", "SHY",
    "SPY", "QQQ", "IWM",
    "HYG", "LQD", "JNK",
    "DXY", "UUP",
]

# Default event store base directory
DEFAULT_EVENT_STORE_DIR: str = "data/event_store"


# ============================================================
# Result dataclasses — output contracts
# ============================================================

@dataclass
class DayTRunResult:
    """Result of a Day T shadow run.

    Attributes:
        date: The snapshot date (YYYY-MM-DD).
        batch: The BatchShadowRun generated by the aggregator.
        report: Formatted ShadowReport (text + JSON).
        events_written: Total events appended to the EventStore.
        store_path: Absolute path to the EventStore directory.
    """
    date: str = ""
    batch: Optional[BatchShadowRun] = None
    report: Optional[ShadowReport] = None
    events_written: int = 0
    store_path: str = ""


@dataclass
class DayTPlus1RunResult:
    """Result of a Day T+1 shadow reconciliation run.

    Attributes:
        date: The T+1 reconciliation date (YYYY-MM-DD).
        previous_date: The T snapshot date that this run judges.
        verdicts: List of TribunalVerdicts rendered.
        summary: Formatted TribunalSummary.
        events_written: Total verdict events appended to the EventStore.
        store_path: Absolute path to the EventStore directory.
    """
    date: str = ""
    previous_date: str = ""
    verdicts: List[TribunalVerdict] = field(default_factory=list)
    summary: Optional[TribunalSummary] = None
    events_written: int = 0
    store_path: str = ""


@dataclass
class FullRunResult:
    """Combined result of a complete Day T → Day T+1 pipeline execution.

    Attributes:
        day_t: The Day T snapshot result.
        day_t_plus_1: The Day T+1 reconciliation result.
        total_events: Sum of all events written across both stages.
    """
    day_t: Optional[DayTRunResult] = None
    day_t_plus_1: Optional[DayTPlus1RunResult] = None
    total_events: int = 0


# ============================================================
# Pipeline Orchestrator
# ============================================================

class DailyShadowRunPipeline:
    """Phase 8.1 Daily Shadow Run Pipeline Orchestrator.

    Two-stage lifecycle:
      1. execute_day_t() — Market snapshot → predictions → store → format
      2. execute_day_t_plus_1() — T+1 actuals → tribunal → store → format

    The orchestrator composes existing Phase 8 modules without modifying
    their interfaces.  All writes to the EventStore are append-only with
    fsync guarantees.

    Args:
        store_dir: Directory path for the EventStore JSONL files.
        ticker_pool: List of tickers to run. Defaults to DEFAULT_SHADOW_POOL.
        run_aggressive: If True, generate aggressive scenarios.
        run_ambiguous: If True, generate ambiguous scenarios.
        strict_mode: If True, tribunal uses strict zero-hedging enforcement.
        replayer_seed: Seed for deterministic MarketDataReplayer.
    """

    def __init__(
        self,
        store_dir: str = DEFAULT_EVENT_STORE_DIR,
        ticker_pool: Optional[List[str]] = None,
        run_aggressive: bool = True,
        run_ambiguous: bool = True,
        strict_mode: bool = True,
        replayer_seed: int = 42,
    ) -> None:
        self._store_dir = store_dir
        self._ticker_pool = list(ticker_pool) if ticker_pool is not None else list(DEFAULT_SHADOW_POOL)
        self._run_aggressive = run_aggressive
        self._run_ambiguous = run_ambiguous
        self._strict_mode = strict_mode
        self._replayer_seed = replayer_seed

        # Lazy-initialised components (created per-run or on first access)
        self._replayer: Optional[MarketDataReplayer] = None
        self._aggregator: Optional[ShadowAggregator] = None
        self._validator: Optional[ZeroHedgingValidator] = None
        self._tribunal: Optional[ShadowTribunal] = None
        self._formatter: Optional[ShadowFormatter] = None
        self._store: Optional[EventStore] = None

    # ------------------------------------------------------------------
    # Component initialisation (lazy)
    # ------------------------------------------------------------------

    @property
    def store(self) -> EventStore:
        """Lazy-initialised EventStore."""
        if self._store is None:
            self._store = EventStore(base_dir=self._store_dir)
        return self._store

    @property
    def replayer(self) -> MarketDataReplayer:
        """Lazy-initialised MarketDataReplayer."""
        if self._replayer is None:
            self._replayer = MarketDataReplayer(seed=self._replayer_seed)
        return self._replayer

    @property
    def aggregator(self) -> ShadowAggregator:
        """Lazy-initialised ShadowAggregator."""
        if self._aggregator is None:
            self._aggregator = ShadowAggregator()
        return self._aggregator

    @property
    def validator(self) -> ZeroHedgingValidator:
        """Lazy-initialised ZeroHedgingValidator."""
        if self._validator is None:
            self._validator = ZeroHedgingValidator(strict_mode=self._strict_mode)
        return self._validator

    @property
    def tribunal(self) -> ShadowTribunal:
        """Lazy-initialised ShadowTribunal."""
        if self._tribunal is None:
            self._tribunal = ShadowTribunal(
                replayer=self.replayer,
                event_store=self.store,
                strict_mode=self._strict_mode,
            )
        return self._tribunal

    @property
    def formatter(self) -> ShadowFormatter:
        """Lazy-initialised ShadowFormatter."""
        if self._formatter is None:
            self._formatter = ShadowFormatter()
        return self._formatter

    # ------------------------------------------------------------------
    # Pipeline stages
    # ------------------------------------------------------------------

    def execute_day_t(self, date: Optional[str] = None) -> DayTRunResult:
        """Execute the Day T snapshot pipeline.

        Flow:
          1. Resolve date (default: today).
          2. ShadowAggregator.run_batch() → predictions for all tickers.
          3. ZeroHedgingValidator.validate_batch() → sanitise hedge words.
          4. EventStore.append_batch() → immutable audit trail (fsync'd).
          5. ShadowFormatter.format_batch_report() → text + JSON output.

        Args:
            date: Snapshot date (YYYY-MM-DD). Defaults to today.

        Returns:
            DayTRunResult with batch, report, and event store metadata.

        Raises:
            RuntimeError: If any pipeline stage fails.
        """
        run_date = date or datetime.datetime.now().strftime("%Y-%m-%d")
        logger.info("[Day T] Starting shadow snapshot for %d tickers on %s",
                     len(self._ticker_pool), run_date)

        # ── Stage 1: Aggregation ──
        # ShadowAggregator.generate(tickers, mode) produces scenarios for a single mode.
        # We compose up to two calls (aggressive + ambiguous) and merge into one batch.
        logger.info("[Day T] Generating predictions via ShadowAggregator...")
        try:
            from copy import deepcopy
            batches: List[BatchShadowRun] = []
            if self._run_aggressive:
                batches.append(self.aggregator.generate(
                    tickers=self._ticker_pool,
                    mode=ShadowMode.AGGRESSIVE,
                ))
            if self._run_ambiguous:
                batches.append(self.aggregator.generate(
                    tickers=self._ticker_pool,
                    mode=ShadowMode.AMBIGUOUS,
                ))
            if not batches:
                # Fallback: STRICT mode (ambiguous scenarios, no aggressive)
                batches.append(self.aggregator.generate(
                    tickers=self._ticker_pool,
                    mode=ShadowMode.STRICT,
                ))

            # Merge all batches into one (take metadata from first batch)
            # BatchShadowRun is frozen — must use constructor
            first = batches[0]
            all_scenarios: List[ShadowScenario] = []
            for b in batches:
                all_scenarios.extend(b.scenarios)
            merged = BatchShadowRun(
                tickers=first.tickers,
                scenarios=all_scenarios,
                mode=first.mode,
                batch_id=first.batch_id,
                generated_at=first.generated_at,
                source_reports=first.source_reports,
                account_snapshot_id=first.account_snapshot_id,
            )
            # total_predictions is auto-computed in __post_init__
            batch = merged
        except Exception as e:
            raise RuntimeError(f"Day T aggregation failed: {e}") from e

        # ── Stage 2: Zero-Hedging validation ──
        logger.info("[Day T] Sanitising %d scenarios via ZeroHedgingValidator...",
                    len(batch.scenarios))
        try:
            validated_batch = self.validator.validate_batch(batch)
        except Exception as e:
            raise RuntimeError(f"Day T zero-hedging validation failed: {e}") from e

        # ── Stage 3: Immutable EventStore persist ──
        logger.info("[Day T] Persisting batch to EventStore (append-only, fsync)...")
        try:
            self.store.append_batch(validated_batch)
            event_count = 1  # one batch event

            # Also persist each prediction individually (granular trail)
            for scenario in validated_batch.scenarios:
                for prediction in scenario.predictions:
                    self.store.append_prediction(prediction)
                    event_count += 1

            logger.info("[Day T] EventStore: %d events written", event_count)
        except Exception as e:
            raise RuntimeError(f"Day T EventStore write failed: {e}") from e

        # ── Stage 4: Format report ──
        logger.info("[Day T] Formatting shadow report...")
        try:
            report = self.formatter.format_batch_report(
                validated_batch,
                include_json=True,
            )
        except Exception as e:
            raise RuntimeError(f"Day T report formatting failed: {e}") from e

        result = DayTRunResult(
            date=run_date,
            batch=validated_batch,
            report=report,
            events_written=event_count,
            store_path=str(Path(self._store_dir).resolve()),
        )

        logger.info("[Day T] Pipeline complete: batch=%s events=%d",
                     validated_batch.batch_id[:12], event_count)
        return result

    def execute_day_t_plus_1(
        self,
        day_t_result: DayTRunResult,
        date: Optional[str] = None,
    ) -> DayTPlus1RunResult:
        """Execute the Day T+1 reconciliation pipeline.

        Flow:
          1. Resolve date (default: today).
          2. ShadowTribunal.judge_batch() → PASS/FAIL verdicts using T+1 actuals.
          3. EventStore.append_verdicts_batch() → immutable verdict trail (fsync'd).
          4. ShadowFormatter.format_tribunal_summary() → summary output.

        Args:
            day_t_result: The DayTRunResult from execute_day_t().
            date: T+1 reconciliation date (YYYY-MM-DD). Defaults to today.

        Returns:
            DayTPlus1RunResult with verdicts, summary, and event store metadata.

        Raises:
            RuntimeError: If any pipeline stage fails.
            ValueError: If day_t_result has no batch.
        """
        if day_t_result.batch is None:
            raise ValueError("DayTPlus1RunResult requires day_t_result.batch to be set")

        run_date = date or datetime.datetime.now().strftime("%Y-%m-%d")
        previous_date = day_t_result.date
        logger.info("[Day T+1] Starting reconciliation for batch %s on %s",
                     day_t_result.batch.batch_id[:12], run_date)

        # ── Stage 1: Tribunal judgment ──
        logger.info("[Day T+1] Running ShadowTribunal...")
        try:
            verdicts = self.tribunal.judge_batch(
                batch=day_t_result.batch,
                previous_date=previous_date,
            )
        except Exception as e:
            raise RuntimeError(f"Day T+1 tribunal failed: {e}") from e

        # ── Stage 2: Immutable EventStore persist ──
        # append_verdicts_batch writes all verdicts atomically under a single lock.
        # We do NOT also write individually — that would cause double-writes.
        logger.info("[Day T+1] Persisting %d verdicts to EventStore (append-only, fsync)...",
                    len(verdicts))
        try:
            self.store.append_verdicts_batch(verdicts)
            event_count = len(verdicts)

            logger.info("[Day T+1] EventStore: %d events written", event_count)
        except Exception as e:
            raise RuntimeError(f"Day T+1 EventStore write failed: {e}") from e

        # ── Stage 3: Format tribunal summary ──
        logger.info("[Day T+1] Formatting tribunal summary...")
        try:
            summary = self.formatter.format_tribunal_summary(
                batch=day_t_result.batch,
                verdicts=verdicts,
            )
        except Exception as e:
            raise RuntimeError(f"Day T+1 tribunal formatting failed: {e}") from e

        result = DayTPlus1RunResult(
            date=run_date,
            previous_date=previous_date,
            verdicts=verdicts,
            summary=summary,
            events_written=event_count,
            store_path=str(Path(self._store_dir).resolve()),
        )

        logger.info("[Day T+1] Pipeline complete: verdicts=%d events=%d",
                     len(verdicts), event_count)
        return result

    def execute_full_run(
        self,
        day_t_date: Optional[str] = None,
        day_t_plus_1_date: Optional[str] = None,
    ) -> FullRunResult:
        """Execute a complete Day T → Day T+1 pipeline end-to-end.

        This is a convenience method that chains execute_day_t() and
        execute_day_t_plus_1() in sequence, propagating the Day T result
        as input to the T+1 reconciliation.

        Args:
            day_t_date: Snapshot date for Day T. Defaults to today.
            day_t_plus_1_date: Reconciliation date for Day T+1. Defaults to today.

        Returns:
            FullRunResult combining both stages.

        Raises:
            RuntimeError: If either pipeline stage fails.
        """
        logger.info("[Full Run] Starting complete Day T → Day T+1 pipeline")

        day_t_result = self.execute_day_t(date=day_t_date)
        day_t_plus_1_result = self.execute_day_t_plus_1(
            day_t_result=day_t_result,
            date=day_t_plus_1_date,
        )

        total = day_t_result.events_written + day_t_plus_1_result.events_written

        result = FullRunResult(
            day_t=day_t_result,
            day_t_plus_1=day_t_plus_1_result,
            total_events=total,
        )

        logger.info("[Full Run] Complete: DayT=%d events | DayT+1=%d events | total=%d",
                     day_t_result.events_written,
                     day_t_plus_1_result.events_written,
                     total)
        return result

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def ticker_pool(self) -> List[str]:
        """The ticker pool configured for this pipeline."""
        return list(self._ticker_pool)

    @property
    def store_dir(self) -> str:
        """The EventStore directory path."""
        return self._store_dir